---
- name: Install apache server   # name of the playbook
  hosts: all    # target group defined in the inventory file 
  become: yes
  tasks:
    - name: install apache server   # name of the play
      become: yes
      apt:
        name: apache2
        state: latest
        update_cache: yes
    - name: start and enable autostart of apache server
      systemd:
        name: apache2
        state: started
        enabled: yes

